# Coastal altimetry tide model rankings

This code compares multiple global ocean tide models against satellite altimetry data, and returns tide model performance and rankings in a standardised format for further analysis.

X-Track coastal altimetry data (v2.1, [10.24400/527896/a01-2022.020](doi.org/10.24400/527896/a01-2022.020)) used in this study were developed, validated by the CTOH/LEGOS, France and distributed by Aviso+.

> Birol, F., N. Fuller, F. Lyard, M. Cancet, F. Niño, C. Delebecque, S. Fleury, F. Toublanc, A. Melet, M. Saraceno, F. Léger, 2017. “Coastal Applications from Nadir Altimetry: Example of the X-TRACK Regional Products.” Advances in Space Research, 2017, 59 (4), p.936-953. doi:10.1016/j.asr.2016.11.005

## Getting started
Set working directory to top level of repo to ensure links work correctly:

In [1]:
cd ../..

/home/jovyan/Robbi/dea-intertidal

Install additional packages directly from the requirements file

In [ ]:
pip install -r requirements.in --quiet

### Load packages

In [2]:
%load_ext autoreload
%autoreload 2

import os
import os.path
import sys
import glob
import tqdm
import datetime
import numpy as np
import xarray as xr
import pandas as pd
import geopandas as gpd
from ftplib import FTP

from eo_tides.model import model_tides

# Set paths to data
tide_model_dir = "/var/share/tide_models/"
altimetry_path = "/gdata1/data/altimetry/X-TRACK/"

# Models to run
models = [
    "EOT20",
    "FES2012",
    "FES2014_extrapolated",
    "FES2022_extrapolated",
    "HAMTIDE11",
    "GOT4.10",
    "GOT5.6_extrapolated",
    "TPXO10-atlas-v2-nc",
    "TPXO8-atlas-nc",
    "TPXO9-atlas-v5-nc",
]

### Preprocess altimetry data

In [3]:
# Load Collection 3 summary grid, reproject to Albers
c3_path = "https://data.dea.ga.gov.au/derivative/ga_summary_grid_c3.geojson"
c3_grid = gpd.read_file(c3_path)
xmin, ymin, xmax, ymax = c3_grid.total_bounds

# Choose which data to load
# paths = glob.glob(f"{altimetry_path}/ctoh.sla.ref.*.nc")  # All files
paths = glob.glob(f"{altimetry_path}/ctoh.sla.ref.S3A*.nc")  # Sentinel-3 only
# paths = glob.glob(f"{altimetry_path}/ctoh.sla.ref.TP+*.nc")  # Topex/Jason-1/Jason-2/Jason-3
# paths = glob.glob(f"{altimetry_path}/ctoh.sla.ref.TPN*.nc")  # Topex/Jason-1/Jason-2 Interleaved orbit
# paths = glob.glob(f"{altimetry_path}/ctoh.sla.ref.TP*.nc")  # All Topex/Jason-1/Jason-2/Jason-3
# paths = glob.glob(f"{altimetry_path}/ctoh.sla.ref.ERS1*.nc")  # ERS-1/ERS-2/Envisat/SARAL/AltiKa
# paths = glob.glob(f"{altimetry_path}/ctoh.sla.ref.HY2*.nc")  # Haiyang-2A
# paths = glob.glob(f"{altimetry_path}/ctoh.sla.ref.GFO*.nc")  # Geosat Follow On

out = []

for path in tqdm.tqdm(paths):
    ds = xr.open_dataset(path, decode_times=False)
    ds_clean = (
        ds[["time", "ocean_tide", "sla", "solid_tide", "mssh"]]
        # Subset to study area
        .sel(
            points_numbers=(ds.lon > xmin)
            & (ds.lon < xmax)
            & (ds.lat > ymin)
            & (ds.lat < ymax)
        )
        # Combine point and cycle dimensions into a single "z" dim
        # so we can convert to a table-like dataframe
        .stack({"z": ["points_numbers", "cycles_numbers"]})
        .to_dataframe()
        # Add satellite series and pass info as a variable
        .assign(pass_number=ds.pass_number, satellites=path.split(".")[3])
        # Remove any rows with missing Sea Level Anomaly or tide data
        .dropna(how="any", axis=0, subset=["sla", "ocean_tide"])
        .reset_index(drop=True)
    )
    out.append(ds_clean)

# Combine
df = pd.concat(out, axis=0)

# Fix time
df["time"] = datetime.datetime(1950, 1, 1) + pd.to_timedelta(df.time, unit="days")

# Remove duplicates
df = df.loc[~df[["time", "lat", "lon"]].duplicated()]

100%|██████████| 206/206 [01:35<00:00,  2.15it/s]

#### Select subset

In [4]:
# Select subset
# df_subset = df
# df_subset = df.iloc[::1000]
# df_subset = df.iloc[0:30000]
# df_subset = df_subset.iloc[0:100000]
df_subset = df.query("lon==111.84197313580249")
# df_subset = df.loc[(df.time >= "2017") & (df.time < "2020")]

# Preview
df_subset

,time,ocean_tide,sla,solid_tide,mssh,lat,lon,points_numbers,cycles_numbers,pass_number,satellites
16639,2016-03-28 02:24:37.999999955,0.5834,0.004584,-0.1001,1.90284,-12.850278,111.841973,386,1,434,S3A
16640,2016-04-24 02:24:36.000000115,0.9147,-0.005295,-0.0351,1.90284,-12.850278,111.841973,386,2,434,S3A
16641,2016-05-21 02:24:38.999999871,0.7335,0.060748,0.0678,1.90284,-12.850278,111.841973,386,3,434,S3A
16642,2016-06-17 02:24:40.000000106,0.1645,0.043066,0.0994,1.90284,-12.850278,111.841973,386,4,434,S3A
16643,2016-07-14 02:24:38.999999871,-0.2854,0.040589,0.0218,1.90284,-12.850278,111.841973,386,5,434,S3A
...,...,...,...,...,...,...,...,...,...,...,...
16726,2022-09-29 02:24:59.000000149,0.5972,0.160225,-0.0409,1.90284,-12.850278,111.841973,386,89,434,S3A
16727,2022-10-26 02:24:57.999999913,0.7303,-0.151912,0.1386,1.90284,-12.850278,111.841973,386,90,434,S3A
16728,2022-11-22 02:24:54.999999846,0.2526,-0.030682,0.2523,1.90284,-12.850278,111.841973,386,91,434,S3A
16729,2022-12-19 02:24:54.999999846,-0.2684,-0.049296,0.1609,1.90284,-12.850278,111.841973,386,92,434,S3A
16730,2023-01-15 02:24:56.999999998,-0.2675,0.000507,-0.0177,1.90284,-12.850278,111.841973,386,93,434,S3A

## Tide modelling

In [9]:
%%time
tide_df = model_tides(
    x=df_subset.lon,
    y=df_subset.lat,
    time=df_subset.time,
    model=models,
    mode="one-to-one",
    output_format="wide",
    directory=tide_model_dir,
    crop_buffer=5,
)
tide_df

Modelling tides with EOT20, FES2012, FES2014_extrapolated, FES2022_extrapolated, HAMTIDE11, GOT4.10, GOT5.6_extrapolated, TPXO10-atlas-v2-nc, TPXO8-atlas-nc, TPXO9-atlas-v5-nc in parallel (models: 10, splits: 1)

100%|██████████| 10/10 [00:11<00:00,  1.15s/it]

Converting to a wide format dataframe
CPU times: user 116 ms, sys: 271 ms, total: 387 ms
Wall time: 12 s

,,tide_model,EOT20,FES2012,FES2014_extrapolated,FES2022_extrapolated,GOT4.10,GOT5.6_extrapolated,HAMTIDE11,TPXO10-atlas-v2-nc,TPXO8-atlas-nc,TPXO9-atlas-v5-nc
time,x,y,,,,,,,,,,
2016-03-28 02:24:37.999999955,111.841973,-12.850278,0.574376,0.597122,0.607787,0.595221,0.592126,0.603051,0.592557,0.607288,0.594505,0.605100
2016-04-24 02:24:36.000000115,111.841973,-12.850278,0.953167,0.938141,0.946868,0.944197,0.969894,0.951886,0.952750,0.978114,0.966177,0.981435
2016-05-21 02:24:38.999999871,111.841973,-12.850278,0.795004,0.779606,0.758824,0.765734,0.774274,0.761429,0.779910,0.778337,0.768659,0.778060
2016-06-17 02:24:40.000000106,111.841973,-12.850278,0.232019,0.188979,0.168233,0.176101,0.179625,0.171436,0.205682,0.184967,0.179637,0.178268
2016-07-14 02:24:38.999999871,111.841973,-12.850278,-0.220406,-0.286067,-0.301456,-0.293536,-0.272823,-0.282626,-0.255276,-0.264876,-0.263968,-0.272506
...,...,...,...,...,...,...,...,...,...,...,...,...
2022-09-29 02:24:59.000000149,111.841973,-12.850278,0.635460,0.592425,0.621891,0.612981,0.596562,0.602104,0.596791,0.624188,0.594995,0.620123
2022-10-26 02:24:57.999999913,111.841973,-12.850278,0.736167,0.723327,0.740499,0.738589,0.735685,0.740987,0.724569,0.772057,0.731541,0.776869
2022-11-22 02:24:54.999999846,111.841973,-12.850278,0.222258,0.249747,0.239631,0.243250,0.240800,0.252282,0.239586,0.272418,0.240996,0.280734
2022-12-19 02:24:54.999999846,111.841973,-12.850278,-0.320516,-0.293937,-0.282663,-0.288618,-0.288534,-0.291476,-0.281084,-0.267564,-0.279895,-0.269250
2023-01-15 02:24:56.999999998,111.841973,-12.850278,-0.315039,-0.279294,-0.254694,-0.269939,-0.287259,-0.304409,-0.268746,-0.264670,-0.275543,-0.278290

### Apply tide correction using each model

In [6]:
# Add non-tide corrected SLA data to dataframe
tide_df["sla_notidecorr"] = (df_subset.sla + df_subset.ocean_tide).values

# Add satellite annotation
tide_df["satellites"] = df_subset.satellites.values

# Reshape to long format
tide_df_long = tide_df.melt(
    ignore_index=False,
    id_vars=["satellites", "sla_notidecorr"],
    value_vars=models,
    value_name="tide_m",
)

# Re-apply tide correction with each of our models
tide_df_long["sla_tidecorr"] = tide_df_long.sla_notidecorr - tide_df_long.tide_m
tide_df_long

,,,satellites,sla_notidecorr,tide_model,tide_m,sla_tidecorr
time,x,y,,,,,
2016-03-28 02:24:37.999999955,111.841973,-12.850278,S3A,0.587984,EOT20,0.574376,0.013608
2016-04-24 02:24:36.000000115,111.841973,-12.850278,S3A,0.909405,EOT20,0.953167,-0.043762
2016-05-21 02:24:38.999999871,111.841973,-12.850278,S3A,0.794248,EOT20,0.795004,-0.000756
2016-06-17 02:24:40.000000106,111.841973,-12.850278,S3A,0.207566,EOT20,0.232019,-0.024454
2016-07-14 02:24:38.999999871,111.841973,-12.850278,S3A,-0.244811,EOT20,-0.220406,-0.024405
...,...,...,...,...,...,...,...
2022-09-29 02:24:59.000000149,111.841973,-12.850278,S3A,0.757425,TPXO9-atlas-v5-nc,0.620123,0.137302
2022-10-26 02:24:57.999999913,111.841973,-12.850278,S3A,0.578388,TPXO9-atlas-v5-nc,0.776869,-0.198481
2022-11-22 02:24:54.999999846,111.841973,-12.850278,S3A,0.221918,TPXO9-atlas-v5-nc,0.280734,-0.058816
2022-12-19 02:24:54.999999846,111.841973,-12.850278,S3A,-0.317696,TPXO9-atlas-v5-nc,-0.269250,-0.048446
2023-01-15 02:24:56.999999998,111.841973,-12.850278,S3A,-0.266993,TPXO9-atlas-v5-nc,-0.278290,0.011297

### Calculate RMS error at every point and model

In [7]:
# Calculate RMS for every model at each point
tide_df_long["sla_tidecorr_sq"] = tide_df_long[["sla_tidecorr"]] ** 2
df_rms = (
    np.sqrt(
        tide_df_long.groupby(["x", "y", "tide_model", "satellites"])[
            ["sla_tidecorr_sq"]
        ].mean()
    )
    .unstack("tide_model")["sla_tidecorr_sq"]
    .reset_index()
)
df_rms

tide_model,x,y,satellites,EOT20,FES2012,FES2014_extrapolated,FES2022_extrapolated,GOT4.10,GOT5.6_extrapolated,HAMTIDE11,TPXO10-atlas-v2-nc,TPXO8-atlas-nc,TPXO9-atlas-v5-nc
0,111.841973,-12.850278,S3A,0.09533,0.101619,0.103278,0.102801,0.101596,0.10163,0.102935,0.104623,0.10206,0.104516

### Filter to points with sufficient observations

In [ ]:
# Add number of observed timesteps
df_rms["n"] = (
    tide_df_long
    .query("tide_model == 'EOT20'")
    .groupby(["x", "y", "satellites"])
    .size()
).values

# Filter to observations with three years of data
df_rms = df_rms.query("n > 20")
df_rms

### Process to standard format

In [ ]:
combined_df = (
    df_rms.rename_axis("point_id")
    .assign(valid_perc=1.0, statistic="rms")
    .rename({"satellites": "source"}, axis=1)
    .reindex(["x", "y", "valid_perc", "source", "statistic"] + models, axis=1)
)

# Update source
combined_df["source"] = "x-track altimetry (" + combined_df.source + ")"

# Add additional columns
combined_df["min"] = combined_df.loc[:, models].min(axis=1)
combined_df["max"] = combined_df.loc[:, models].max(axis=1)
combined_df["diff"] = combined_df["max"] - combined_df["min"]
combined_df["ave"] = combined_df.loc[:, models].mean(axis=1)
combined_df["median"] = combined_df.loc[:, models].median(axis=1)
combined_df["std"] = combined_df.loc[:, models].std(axis=1)
combined_df["missing"] = combined_df.loc[:, models].isna().sum(axis=1)

# Calculate ranks and best/worst models
combined_df = pd.concat(
    [combined_df, combined_df.loc[:, models].rank(axis=1, ascending=True).add_prefix("rank_")], axis=1
)
combined_df["top_model"] = combined_df.filter(regex='^rank').idxmin(axis=1).str[5:]
combined_df["worst_model"] = combined_df.filter(regex='^rank').idxmax(axis=1).str[5:]
combined_df

### Export

In [ ]:
# pip install pyogrio

In [ ]:
# Export to GeoJSON
xtrack_rms_gdf = gpd.GeoDataFrame(
    data=combined_df,
    geometry=gpd.points_from_xy(x=combined_df.x, y=combined_df.y),
    crs="EPSG:4326",
)
xtrack_rms_gdf.to_file(f"data/raw/rankings_altimetry_2017-2019.fgb", engine="pyogrio")